sys := "trustm-sys"
lib := "optiga-trust-m"

default:
    @just --list

build:
    cargo build

test:
    cargo test

lint:
    cargo fmt --check
    cargo clippy --all-targets -- -D warnings

# Static aarch64 build (needs aarch64-linux-musl-gcc)
release:
    cargo build --release --target aarch64-unknown-linux-musl

# Regenerate trustm-sys/src/bindings.rs from the submodule's headers (needs bindgen + libclang)
bindgen:
    bindgen {{sys}}/csrc/wrapper.h -o {{sys}}/src/bindings.rs \
      --allowlist-function '(optiga|pal|ifx|trustm)_.*' --allowlist-type '(optiga|pal|ifx)_.*' --allowlist-var '(OPTIGA|PAL|IFX)_.*' \
      --opaque-type 'ifx_i2c_context.*' --default-enum-style moduleconsts --no-doc-comments \
      --raw-line '// Generated by bindgen from csrc/wrapper.h. Do not edit; run `just bindgen`.' \
      -- -I{{sys}}/csrc -I{{lib}}/include -I{{lib}}/include/pal -I{{lib}}/include/common -I{{lib}}/include/comms \
         -I{{lib}}/include/cmd -I{{lib}}/include/ifx_i2c -I{{lib}}/extras/pal/linux/include \
         -DOPTIGA_LIB_EXTERNAL='"trustm_sys_config.h"'

ci: lint build test

clean:
    cargo clean
