/* automatically generated by rust-bindgen 0.71.1 */

// Generated by bindgen from csrc/wrapper.h. Do not edit; run `just bindgen`.

#[doc = r" If Bindgen could only determine the size and alignment of a"]
#[doc = r" type, it is represented like this."]
#[derive(PartialEq, Copy, Clone, Debug, Hash)]
#[repr(C)]
pub struct __BindgenOpaqueArray<T: Copy, const N: usize>(pub [T; N]);
impl<T: Copy + Default, const N: usize> Default for __BindgenOpaqueArray<T, N> {
    fn default() -> Self {
        Self([<T as Default>::default(); N])
    }
}
pub const OPTIGA_COMMS_DEFAULT_RESET_TYPE: u32 = 1;
pub const OPTIGA_CMD_MAX_REGISTRATIONS: u32 = 6;
pub const OPTIGA_MAX_COMMS_BUFFER_SIZE: u32 = 1557;
pub const OPTIGA_LIB_SUCCESS: u32 = 0;
pub const OPTIGA_LIB_BUSY: u32 = 1;
pub const OPTIGA_DEVICE_ERROR: u32 = 32768;
pub const OPTIGA_COMMS_SUCCESS: u32 = 0;
pub const OPTIGA_COMMS_BUSY: u32 = 1;
pub const OPTIGA_COMMS_ERROR: u32 = 258;
pub const OPTIGA_COMMS_ERROR_INVALID_INPUT: u32 = 259;
pub const OPTIGA_COMMS_ERROR_MEMORY_INSUFFICIENT: u32 = 260;
pub const OPTIGA_COMMS_ERROR_STACK_MEMORY: u32 = 261;
pub const OPTIGA_COMMS_ERROR_FATAL: u32 = 262;
pub const OPTIGA_COMMS_ERROR_HANDSHAKE: u32 = 263;
pub const OPTIGA_COMMS_ERROR_SESSION: u32 = 264;
pub const OPTIGA_CMD_SUCCESS: u32 = 0;
pub const OPTIGA_CMD_BUSY: u32 = 1;
pub const OPTIGA_CMD_ERROR: u32 = 514;
pub const OPTIGA_CMD_ERROR_INVALID_INPUT: u32 = 515;
pub const OPTIGA_CMD_ERROR_MEMORY_INSUFFICIENT: u32 = 516;
pub const OPTIGA_UTIL_SUCCESS: u32 = 0;
pub const OPTIGA_UTIL_BUSY: u32 = 1;
pub const OPTIGA_UTIL_ERROR: u32 = 770;
pub const OPTIGA_UTIL_ERROR_INVALID_INPUT: u32 = 771;
pub const OPTIGA_UTIL_ERROR_MEMORY_INSUFFICIENT: u32 = 772;
pub const OPTIGA_UTIL_ERROR_INSTANCE_IN_USE: u32 = 773;
pub const OPTIGA_CRYPT_SUCCESS: u32 = 0;
pub const OPTIGA_CRYPT_BUSY: u32 = 1;
pub const OPTIGA_CRYPT_ERROR: u32 = 1026;
pub const OPTIGA_CRYPT_ERROR_INVALID_INPUT: u32 = 1027;
pub const OPTIGA_CRYPT_ERROR_MEMORY_INSUFFICIENT: u32 = 1028;
pub const OPTIGA_CRYPT_ERROR_INSTANCE_IN_USE: u32 = 1029;
pub const OPTIGA_INSTANCE_ID_0: u32 = 0;
pub const OPTIGA_COMMS_NO_PROTECTION: u32 = 0;
pub const OPTIGA_COMMS_COMMAND_PROTECTION: u32 = 1;
pub const OPTIGA_COMMS_RESPONSE_PROTECTION: u32 = 2;
pub const OPTIGA_COMMS_FULL_PROTECTION: u32 = 3;
pub const OPTIGA_COMMS_RE_ESTABLISH: u32 = 128;
pub const OPTIGA_COMMS_PROTOCOL_VERSION_PRE_SHARED_SECRET: u32 = 1;
pub const OPTIGA_CRYPT_HOST_DATA: u32 = 1;
pub const OPTIGA_CRYPT_OID_DATA: u32 = 0;
pub const OPTIGA_LIB_INSTANCE_BUSY: u32 = 1;
pub const OPTIGA_LIB_INSTANCE_FREE: u32 = 0;
pub const OPTIGA_UTIL_WRITE_ONLY: u32 = 0;
pub const OPTIGA_UTIL_ERASE_AND_WRITE: u32 = 64;
pub const OPTIGA_UTIL_CONTEXT_NONE: u32 = 0;
pub const OPTIGA_LAYER_EMPTY: &[u8; 9] = b"        \0";
pub const OPTIGA_UTIL_SERVICE: &[u8; 9] = b"[util]  \0";
pub const OPTIGA_CRYPT_SERVICE: &[u8; 9] = b"[crypt] \0";
pub const OPTIGA_COMMAND_LAYER: &[u8; 9] = b"[cmd]   \0";
pub const OPTIGA_COMMUNICATION_LAYER: &[u8; 9] = b"[comms] \0";
pub const OPTIGA_PAL_LAYER: &[u8; 9] = b"[pal]   \0";
pub const OPTIGA_LIB_LOGGER_COLOR_RED: &[u8; 6] = b"\x1B[31m\0";
pub const OPTIGA_LIB_LOGGER_COLOR_GREEN: &[u8; 6] = b"\x1B[32m\0";
pub const OPTIGA_LIB_LOGGER_COLOR_YELLOW: &[u8; 6] = b"\x1B[33m\0";
pub const OPTIGA_LIB_LOGGER_COLOR_BLUE: &[u8; 6] = b"\x1B[34m\0";
pub const OPTIGA_LIB_LOGGER_COLOR_MAGENTA: &[u8; 6] = b"\x1B[35m\0";
pub const OPTIGA_LIB_LOGGER_COLOR_CYAN: &[u8; 6] = b"\x1B[36m\0";
pub const OPTIGA_LIB_LOGGER_COLOR_LIGHT_GREY: &[u8; 6] = b"\x1B[90m\0";
pub const OPTIGA_LIB_LOGGER_COLOR_LIGHT_RED: &[u8; 6] = b"\x1B[91m\0";
pub const OPTIGA_LIB_LOGGER_COLOR_LIGHT_GREEN: &[u8; 6] = b"\x1B[92m\0";
pub const OPTIGA_LIB_LOGGER_COLOR_LIGHT_YELLOW: &[u8; 6] = b"\x1B[93m\0";
pub const OPTIGA_LIB_LOGGER_COLOR_LIGHT_BLUE: &[u8; 6] = b"\x1B[94m\0";
pub const OPTIGA_LIB_LOGGER_COLOR_LIGHT_MAGENTA: &[u8; 6] = b"\x1B[95m\0";
pub const OPTIGA_LIB_LOGGER_COLOR_LIGHT_CYAN: &[u8; 6] = b"\x1B[96m\0";
pub const OPTIGA_LIB_LOGGER_COLOR_DEFAULT: &[u8; 5] = b"\x1B[0m\0";
pub const OPTIGA_UTIL_SERVICE_COLOR: &[u8; 5] = b"\x1B[0m\0";
pub const OPTIGA_CRYPT_SERVICE_COLOR: &[u8; 5] = b"\x1B[0m\0";
pub const OPTIGA_COMMAND_LAYER_COLOR: &[u8; 5] = b"\x1B[0m\0";
pub const OPTIGA_COMMUNICATION_LAYER_COLOR: &[u8; 5] = b"\x1B[0m\0";
pub const OPTIGA_ERROR_COLOR: &[u8; 6] = b"\x1B[31m\0";
pub const OPTIGA_UNPROTECTED_DATA_COLOR: &[u8; 6] = b"\x1B[96m\0";
pub const OPTIGA_PROTECTED_DATA_COLOR: &[u8; 6] = b"\x1B[33m\0";
pub const OPTIGA_HEX_BYTE_SEPERATOR: &[u8; 1] = b"\0";
pub const PAL_STATUS_SUCCESS: u32 = 0;
pub const PAL_STATUS_FAILURE: u32 = 1;
pub const PAL_STATUS_I2C_BUSY: u32 = 2;
pub const PAL_STATUS_INVALID_INPUT: u32 = 4;
pub const PAL_I2C_EVENT_SUCCESS: u32 = 0;
pub const PAL_I2C_EVENT_ERROR: u32 = 1;
pub const PAL_I2C_EVENT_BUSY: u32 = 2;
pub const OPTIGA_PLATFORM_BINDING_SHARED_SECRET_ID: u32 = 17;
pub const OPTIGA_SHARED_SECRET_MAX_LENGTH: u32 = 64;
pub const OPTIGA_LIB_PAL_DATA_STORE_NOT_CONFIGURED: u32 = 0;
pub const OPTIGA_COMMS_MANAGE_CONTEXT_ID: u32 = 34;
pub const OPTIGA_HIBERNATE_CONTEXT_ID: u32 = 51;
pub const IFX_I2C_BASE_ADDR: u32 = 48;
pub const IFX_I2C_FRAME_SIZE: u32 = 277;
pub const IFX_I2C_STACK_SUCCESS: u32 = 0;
pub const IFX_I2C_STACK_BUSY: u32 = 1;
pub const IFX_I2C_STACK_ERROR: u32 = 258;
pub const IFX_I2C_STACK_MEM_ERROR: u32 = 260;
pub const IFX_I2C_FATAL_ERROR: u32 = 262;
pub const IFX_I2C_HANDSHAKE_ERROR: u32 = 263;
pub const IFX_I2C_SESSION_ERROR: u32 = 264;
pub const IFX_I2C_DL_HEADER_OFFSET: u32 = 0;
pub const IFX_I2C_TL_HEADER_OFFSET: u32 = 3;
pub const IFX_I2C_LOG_PL: u32 = 0;
pub const IFX_I2C_LOG_DL: u32 = 0;
pub const IFX_I2C_LOG_TL: u32 = 0;
pub const IFX_I2C_LOG_PRL: u32 = 0;
pub const IFX_I2C_LOG_ID_PL: u32 = 0;
pub const IFX_I2C_LOG_ID_DL: u32 = 1;
pub const IFX_I2C_LOG_ID_TL: u32 = 2;
pub const IFX_I2C_LOG_ID_PRL: u32 = 3;
pub const IFX_I2C_LOG_ID_PAL: u32 = 4;
pub const IFX_I2C_PRESENCE_BIT: u32 = 0;
pub const IFX_I2C_PRL_MAC_SIZE: u32 = 0;
pub const IFX_I2C_PRL_HEADER_SIZE: u32 = 0;
pub const IFX_I2C_PRL_OVERHEAD_SIZE: u32 = 0;
pub const IFX_I2C_DATA_OFFSET: u32 = 0;
pub const IFX_I2C_PRESENCE_BIT_CHECK: u32 = 0;
pub const IFX_I2C_SESSION_CONTEXT_RESTORE: u32 = 17;
pub const IFX_I2C_SESSION_CONTEXT_SAVE: u32 = 34;
pub const IFX_I2C_SESSION_CONTEXT_NONE: u32 = 51;
pub const IFX_I2C_SESSION_KEY_BUFFER_SIZE: u32 = 40;
pub const OPTIGA_COMMS_DATA_OFFSET: u32 = 0;
pub const OPTIGA_COMMS_PRL_OVERHEAD: u32 = 0;
pub type char_t = ::std::os::raw::c_char;
pub type bool_t = u8;
pub type optiga_lib_status_t = u16;
pub type upper_layer_callback_t = ::std::option::Option<
    unsafe extern "C" fn(upper_layer_ctx: *mut ::std::os::raw::c_void, event: optiga_lib_status_t),
>;
pub type callback_handler_t = ::std::option::Option<
    unsafe extern "C" fn(callback_ctx: *mut ::std::os::raw::c_void, event: optiga_lib_status_t),
>;
pub mod optiga_key_id {
    pub type Type = ::std::os::raw::c_uint;
    pub const OPTIGA_KEY_ID_E0F0: Type = 57584;
    pub const OPTIGA_KEY_ID_E0F1: Type = 57585;
    pub const OPTIGA_KEY_ID_E0F2: Type = 57586;
    pub const OPTIGA_KEY_ID_E0F3: Type = 57587;
    pub const OPTIGA_KEY_ID_E0FC: Type = 57596;
    pub const OPTIGA_KEY_ID_E0FD: Type = 57597;
    pub const OPTIGA_KEY_ID_SESSION_BASED: Type = 0;
    pub const OPTIGA_KEY_ID_SECRET_BASED: Type = 57856;
}
pub use self::optiga_key_id::Type as optiga_key_id_t;
pub mod optiga_key_usage {
    pub type Type = ::std::os::raw::c_uint;
    pub const OPTIGA_KEY_USAGE_AUTHENTICATION: Type = 1;
    pub const OPTIGA_KEY_USAGE_SIGN: Type = 16;
    pub const OPTIGA_KEY_USAGE_KEY_AGREEMENT: Type = 32;
    pub const OPTIGA_KEY_USAGE_ENCRYPTION: Type = 2;
}
pub use self::optiga_key_usage::Type as optiga_key_usage_t;
pub mod optiga_set_obj_protected_tag {
    pub type Type = ::std::os::raw::c_uint;
    pub const OPTIGA_SET_PROTECTED_UPDATE_START: Type = 0;
    pub const OPTIGA_SET_PROTECTED_UPDATE_CONTINUE: Type = 2;
    pub const OPTIGA_SET_PROTECTED_UPDATE_FINAL: Type = 1;
}
pub use self::optiga_set_obj_protected_tag::Type as optiga_set_obj_protected_tag_t;
pub mod optiga_ecc_curve {
    pub type Type = ::std::os::raw::c_uint;
    pub const OPTIGA_ECC_CURVE_NIST_P_256: Type = 3;
    pub const OPTIGA_ECC_CURVE_NIST_P_384: Type = 4;
    pub const OPTIGA_ECC_CURVE_NIST_P_521: Type = 5;
    pub const OPTIGA_ECC_CURVE_BRAIN_POOL_P_256R1: Type = 19;
    pub const OPTIGA_ECC_CURVE_BRAIN_POOL_P_384R1: Type = 21;
    pub const OPTIGA_ECC_CURVE_BRAIN_POOL_P_512R1: Type = 22;
}
pub use self::optiga_ecc_curve::Type as optiga_ecc_curve_t;
pub mod optiga_rsa_encryption_scheme {
    pub type Type = ::std::os::raw::c_uint;
    pub const OPTIGA_RSAES_PKCS1_V15: Type = 17;
}
pub use self::optiga_rsa_encryption_scheme::Type as optiga_rsa_encryption_scheme_t;
pub mod optiga_rsa_key_type {
    pub type Type = ::std::os::raw::c_uint;
    pub const OPTIGA_RSA_KEY_1024_BIT_EXPONENTIAL: Type = 65;
    pub const OPTIGA_RSA_KEY_2048_BIT_EXPONENTIAL: Type = 66;
}
pub use self::optiga_rsa_key_type::Type as optiga_rsa_key_type_t;
pub mod optiga_rsa_signature_scheme {
    pub type Type = ::std::os::raw::c_uint;
    pub const OPTIGA_RSASSA_PKCS1_V15_SHA256: Type = 1;
    pub const OPTIGA_RSASSA_PKCS1_V15_SHA384: Type = 2;
    pub const OPTIGA_RSASSA_PKCS1_V15_SHA512: Type = 3;
}
pub use self::optiga_rsa_signature_scheme::Type as optiga_rsa_signature_scheme_t;
pub mod optiga_symmetric_encryption_mode {
    pub type Type = ::std::os::raw::c_uint;
    pub const OPTIGA_SYMMETRIC_ECB: Type = 8;
    pub const OPTIGA_SYMMETRIC_CBC: Type = 9;
    pub const OPTIGA_SYMMETRIC_CBC_MAC: Type = 10;
    pub const OPTIGA_SYMMETRIC_CMAC: Type = 11;
}
pub use self::optiga_symmetric_encryption_mode::Type as optiga_symmetric_encryption_mode_t;
pub mod optiga_hash_type {
    pub type Type = ::std::os::raw::c_uint;
    pub const OPTIGA_HASH_TYPE_SHA_256: Type = 226;
}
pub use self::optiga_hash_type::Type as optiga_hash_type_t;
pub mod optiga_hash_context_length {
    pub type Type = ::std::os::raw::c_uint;
    pub const OPTIGA_HASH_CONTEXT_LENGTH_SHA_256: Type = 209;
}
pub use self::optiga_hash_context_length::Type as optiga_hash_context_length_t;
pub mod optiga_rng_type {
    pub type Type = ::std::os::raw::c_uint;
    pub const OPTIGA_RNG_TYPE_TRNG: Type = 0;
    pub const OPTIGA_RNG_TYPE_DRNG: Type = 1;
}
pub use self::optiga_rng_type::Type as optiga_rng_type_t;
pub mod optiga_hmac_type {
    pub type Type = ::std::os::raw::c_uint;
    pub const OPTIGA_HMAC_SHA_256: Type = 32;
    pub const OPTIGA_HMAC_SHA_384: Type = 33;
    pub const OPTIGA_HMAC_SHA_512: Type = 34;
}
pub use self::optiga_hmac_type::Type as optiga_hmac_type_t;
pub mod optiga_hkdf_type {
    pub type Type = ::std::os::raw::c_uint;
    pub const OPTIGA_HKDF_SHA_256: Type = 8;
    pub const OPTIGA_HKDF_SHA_384: Type = 9;
    pub const OPTIGA_HKDF_SHA_512: Type = 10;
}
pub use self::optiga_hkdf_type::Type as optiga_hkdf_type_t;
pub mod optiga_tls_prf_type {
    pub type Type = ::std::os::raw::c_uint;
    pub const OPTIGA_TLS12_PRF_SHA_256: Type = 1;
    pub const OPTIGA_TLS12_PRF_SHA_384: Type = 2;
    pub const OPTIGA_TLS12_PRF_SHA_512: Type = 3;
}
pub use self::optiga_tls_prf_type::Type as optiga_tls_prf_type_t;
pub mod optiga_symmetric_key_type {
    pub type Type = ::std::os::raw::c_uint;
    pub const OPTIGA_SYMMETRIC_AES_128: Type = 129;
    pub const OPTIGA_SYMMETRIC_AES_192: Type = 130;
    pub const OPTIGA_SYMMETRIC_AES_256: Type = 131;
}
pub use self::optiga_symmetric_key_type::Type as optiga_symmetric_key_type_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct optiga_hash_context {
    pub context_buffer: *mut u8,
    pub context_buffer_length: u16,
    pub hash_algo: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_hash_context"][::std::mem::size_of::<optiga_hash_context>() - 16usize];
    ["Alignment of optiga_hash_context"][::std::mem::align_of::<optiga_hash_context>() - 8usize];
    ["Offset of field: optiga_hash_context::context_buffer"]
        [::std::mem::offset_of!(optiga_hash_context, context_buffer) - 0usize];
    ["Offset of field: optiga_hash_context::context_buffer_length"]
        [::std::mem::offset_of!(optiga_hash_context, context_buffer_length) - 8usize];
    ["Offset of field: optiga_hash_context::hash_algo"]
        [::std::mem::offset_of!(optiga_hash_context, hash_algo) - 10usize];
};
pub type optiga_hash_context_t = optiga_hash_context;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hash_data_from_host {
    pub buffer: *const u8,
    pub length: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of hash_data_from_host"][::std::mem::size_of::<hash_data_from_host>() - 16usize];
    ["Alignment of hash_data_from_host"][::std::mem::align_of::<hash_data_from_host>() - 8usize];
    ["Offset of field: hash_data_from_host::buffer"]
        [::std::mem::offset_of!(hash_data_from_host, buffer) - 0usize];
    ["Offset of field: hash_data_from_host::length"]
        [::std::mem::offset_of!(hash_data_from_host, length) - 8usize];
};
pub type hash_data_from_host_t = hash_data_from_host;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hash_data_in_optiga {
    pub oid: u16,
    pub offset: u16,
    pub length: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of hash_data_in_optiga"][::std::mem::size_of::<hash_data_in_optiga>() - 6usize];
    ["Alignment of hash_data_in_optiga"][::std::mem::align_of::<hash_data_in_optiga>() - 2usize];
    ["Offset of field: hash_data_in_optiga::oid"]
        [::std::mem::offset_of!(hash_data_in_optiga, oid) - 0usize];
    ["Offset of field: hash_data_in_optiga::offset"]
        [::std::mem::offset_of!(hash_data_in_optiga, offset) - 2usize];
    ["Offset of field: hash_data_in_optiga::length"]
        [::std::mem::offset_of!(hash_data_in_optiga, length) - 4usize];
};
pub type hash_data_in_optiga_t = hash_data_in_optiga;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct public_key_from_host {
    pub public_key: *mut u8,
    pub length: u16,
    pub key_type: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of public_key_from_host"][::std::mem::size_of::<public_key_from_host>() - 16usize];
    ["Alignment of public_key_from_host"][::std::mem::align_of::<public_key_from_host>() - 8usize];
    ["Offset of field: public_key_from_host::public_key"]
        [::std::mem::offset_of!(public_key_from_host, public_key) - 0usize];
    ["Offset of field: public_key_from_host::length"]
        [::std::mem::offset_of!(public_key_from_host, length) - 8usize];
    ["Offset of field: public_key_from_host::key_type"]
        [::std::mem::offset_of!(public_key_from_host, key_type) - 10usize];
};
pub type public_key_from_host_t = public_key_from_host;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct optiga_get_data_object {
    pub ref_bytes_to_read: *mut u16,
    pub buffer: *mut u8,
    pub oid: u16,
    pub offset: u16,
    pub bytes_to_read: u16,
    pub accumulated_size: u16,
    pub last_read_size: u16,
    pub data_or_metadata: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_get_data_object"][::std::mem::size_of::<optiga_get_data_object>() - 32usize];
    ["Alignment of optiga_get_data_object"]
        [::std::mem::align_of::<optiga_get_data_object>() - 8usize];
    ["Offset of field: optiga_get_data_object::ref_bytes_to_read"]
        [::std::mem::offset_of!(optiga_get_data_object, ref_bytes_to_read) - 0usize];
    ["Offset of field: optiga_get_data_object::buffer"]
        [::std::mem::offset_of!(optiga_get_data_object, buffer) - 8usize];
    ["Offset of field: optiga_get_data_object::oid"]
        [::std::mem::offset_of!(optiga_get_data_object, oid) - 16usize];
    ["Offset of field: optiga_get_data_object::offset"]
        [::std::mem::offset_of!(optiga_get_data_object, offset) - 18usize];
    ["Offset of field: optiga_get_data_object::bytes_to_read"]
        [::std::mem::offset_of!(optiga_get_data_object, bytes_to_read) - 20usize];
    ["Offset of field: optiga_get_data_object::accumulated_size"]
        [::std::mem::offset_of!(optiga_get_data_object, accumulated_size) - 22usize];
    ["Offset of field: optiga_get_data_object::last_read_size"]
        [::std::mem::offset_of!(optiga_get_data_object, last_read_size) - 24usize];
    ["Offset of field: optiga_get_data_object::data_or_metadata"]
        [::std::mem::offset_of!(optiga_get_data_object, data_or_metadata) - 26usize];
};
pub type optiga_get_data_object_params_t = optiga_get_data_object;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct optiga_set_data_object {
    pub buffer: *const u8,
    pub oid: u16,
    pub offset: u16,
    pub size: u16,
    pub written_size: u16,
    pub data_or_metadata: u8,
    pub write_type: u8,
    pub count: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_set_data_object"][::std::mem::size_of::<optiga_set_data_object>() - 24usize];
    ["Alignment of optiga_set_data_object"]
        [::std::mem::align_of::<optiga_set_data_object>() - 8usize];
    ["Offset of field: optiga_set_data_object::buffer"]
        [::std::mem::offset_of!(optiga_set_data_object, buffer) - 0usize];
    ["Offset of field: optiga_set_data_object::oid"]
        [::std::mem::offset_of!(optiga_set_data_object, oid) - 8usize];
    ["Offset of field: optiga_set_data_object::offset"]
        [::std::mem::offset_of!(optiga_set_data_object, offset) - 10usize];
    ["Offset of field: optiga_set_data_object::size"]
        [::std::mem::offset_of!(optiga_set_data_object, size) - 12usize];
    ["Offset of field: optiga_set_data_object::written_size"]
        [::std::mem::offset_of!(optiga_set_data_object, written_size) - 14usize];
    ["Offset of field: optiga_set_data_object::data_or_metadata"]
        [::std::mem::offset_of!(optiga_set_data_object, data_or_metadata) - 16usize];
    ["Offset of field: optiga_set_data_object::write_type"]
        [::std::mem::offset_of!(optiga_set_data_object, write_type) - 17usize];
    ["Offset of field: optiga_set_data_object::count"]
        [::std::mem::offset_of!(optiga_set_data_object, count) - 18usize];
};
pub type optiga_set_data_object_params_t = optiga_set_data_object;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct optiga_calc_hash {
    pub p_hash_oid: *mut hash_data_in_optiga_t,
    pub p_hash_data: *mut hash_data_from_host_t,
    pub p_hash_context: *mut optiga_hash_context_t,
    pub p_out_digest: *mut u8,
    pub data_sent: u32,
    pub apparent_context_size: u32,
    pub hash_sequence: u8,
    pub current_hash_sequence: u8,
    pub export_hash_ctx: bool_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_calc_hash"][::std::mem::size_of::<optiga_calc_hash>() - 48usize];
    ["Alignment of optiga_calc_hash"][::std::mem::align_of::<optiga_calc_hash>() - 8usize];
    ["Offset of field: optiga_calc_hash::p_hash_oid"]
        [::std::mem::offset_of!(optiga_calc_hash, p_hash_oid) - 0usize];
    ["Offset of field: optiga_calc_hash::p_hash_data"]
        [::std::mem::offset_of!(optiga_calc_hash, p_hash_data) - 8usize];
    ["Offset of field: optiga_calc_hash::p_hash_context"]
        [::std::mem::offset_of!(optiga_calc_hash, p_hash_context) - 16usize];
    ["Offset of field: optiga_calc_hash::p_out_digest"]
        [::std::mem::offset_of!(optiga_calc_hash, p_out_digest) - 24usize];
    ["Offset of field: optiga_calc_hash::data_sent"]
        [::std::mem::offset_of!(optiga_calc_hash, data_sent) - 32usize];
    ["Offset of field: optiga_calc_hash::apparent_context_size"]
        [::std::mem::offset_of!(optiga_calc_hash, apparent_context_size) - 36usize];
    ["Offset of field: optiga_calc_hash::hash_sequence"]
        [::std::mem::offset_of!(optiga_calc_hash, hash_sequence) - 40usize];
    ["Offset of field: optiga_calc_hash::current_hash_sequence"]
        [::std::mem::offset_of!(optiga_calc_hash, current_hash_sequence) - 41usize];
    ["Offset of field: optiga_calc_hash::export_hash_ctx"]
        [::std::mem::offset_of!(optiga_calc_hash, export_hash_ctx) - 42usize];
};
pub type optiga_calc_hash_params_t = optiga_calc_hash;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct optiga_get_random {
    pub random_data: *mut u8,
    pub optional_data: *const u8,
    pub random_data_length: u16,
    pub optional_data_length: u16,
    pub store_in_session: bool_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_get_random"][::std::mem::size_of::<optiga_get_random>() - 24usize];
    ["Alignment of optiga_get_random"][::std::mem::align_of::<optiga_get_random>() - 8usize];
    ["Offset of field: optiga_get_random::random_data"]
        [::std::mem::offset_of!(optiga_get_random, random_data) - 0usize];
    ["Offset of field: optiga_get_random::optional_data"]
        [::std::mem::offset_of!(optiga_get_random, optional_data) - 8usize];
    ["Offset of field: optiga_get_random::random_data_length"]
        [::std::mem::offset_of!(optiga_get_random, random_data_length) - 16usize];
    ["Offset of field: optiga_get_random::optional_data_length"]
        [::std::mem::offset_of!(optiga_get_random, optional_data_length) - 18usize];
    ["Offset of field: optiga_get_random::store_in_session"]
        [::std::mem::offset_of!(optiga_get_random, store_in_session) - 20usize];
};
pub type optiga_get_random_params_t = optiga_get_random;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct optiga_gen_keypair {
    pub private_key: *mut u8,
    pub private_key_length: *mut u16,
    pub public_key: *mut u8,
    pub public_key_length: *mut u16,
    pub private_key_oid: optiga_key_id_t,
    pub key_usage: u8,
    pub export_private_key: bool_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_gen_keypair"][::std::mem::size_of::<optiga_gen_keypair>() - 40usize];
    ["Alignment of optiga_gen_keypair"][::std::mem::align_of::<optiga_gen_keypair>() - 8usize];
    ["Offset of field: optiga_gen_keypair::private_key"]
        [::std::mem::offset_of!(optiga_gen_keypair, private_key) - 0usize];
    ["Offset of field: optiga_gen_keypair::private_key_length"]
        [::std::mem::offset_of!(optiga_gen_keypair, private_key_length) - 8usize];
    ["Offset of field: optiga_gen_keypair::public_key"]
        [::std::mem::offset_of!(optiga_gen_keypair, public_key) - 16usize];
    ["Offset of field: optiga_gen_keypair::public_key_length"]
        [::std::mem::offset_of!(optiga_gen_keypair, public_key_length) - 24usize];
    ["Offset of field: optiga_gen_keypair::private_key_oid"]
        [::std::mem::offset_of!(optiga_gen_keypair, private_key_oid) - 32usize];
    ["Offset of field: optiga_gen_keypair::key_usage"]
        [::std::mem::offset_of!(optiga_gen_keypair, key_usage) - 36usize];
    ["Offset of field: optiga_gen_keypair::export_private_key"]
        [::std::mem::offset_of!(optiga_gen_keypair, export_private_key) - 37usize];
};
pub type optiga_gen_keypair_params_t = optiga_gen_keypair;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct optiga_calc_sign {
    pub p_digest: *const u8,
    pub p_signature: *mut u8,
    pub p_signature_length: *mut u16,
    pub private_key_oid: optiga_key_id_t,
    pub digest_length: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_calc_sign"][::std::mem::size_of::<optiga_calc_sign>() - 32usize];
    ["Alignment of optiga_calc_sign"][::std::mem::align_of::<optiga_calc_sign>() - 8usize];
    ["Offset of field: optiga_calc_sign::p_digest"]
        [::std::mem::offset_of!(optiga_calc_sign, p_digest) - 0usize];
    ["Offset of field: optiga_calc_sign::p_signature"]
        [::std::mem::offset_of!(optiga_calc_sign, p_signature) - 8usize];
    ["Offset of field: optiga_calc_sign::p_signature_length"]
        [::std::mem::offset_of!(optiga_calc_sign, p_signature_length) - 16usize];
    ["Offset of field: optiga_calc_sign::private_key_oid"]
        [::std::mem::offset_of!(optiga_calc_sign, private_key_oid) - 24usize];
    ["Offset of field: optiga_calc_sign::digest_length"]
        [::std::mem::offset_of!(optiga_calc_sign, digest_length) - 28usize];
};
pub type optiga_calc_sign_params_t = optiga_calc_sign;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct optiga_verify_sign {
    pub p_digest: *const u8,
    pub p_signature: *const u8,
    pub public_key: *mut public_key_from_host_t,
    pub signature_length: u16,
    pub certificate_oid: u16,
    pub digest_length: u8,
    pub public_key_source_type: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_verify_sign"][::std::mem::size_of::<optiga_verify_sign>() - 32usize];
    ["Alignment of optiga_verify_sign"][::std::mem::align_of::<optiga_verify_sign>() - 8usize];
    ["Offset of field: optiga_verify_sign::p_digest"]
        [::std::mem::offset_of!(optiga_verify_sign, p_digest) - 0usize];
    ["Offset of field: optiga_verify_sign::p_signature"]
        [::std::mem::offset_of!(optiga_verify_sign, p_signature) - 8usize];
    ["Offset of field: optiga_verify_sign::public_key"]
        [::std::mem::offset_of!(optiga_verify_sign, public_key) - 16usize];
    ["Offset of field: optiga_verify_sign::signature_length"]
        [::std::mem::offset_of!(optiga_verify_sign, signature_length) - 24usize];
    ["Offset of field: optiga_verify_sign::certificate_oid"]
        [::std::mem::offset_of!(optiga_verify_sign, certificate_oid) - 26usize];
    ["Offset of field: optiga_verify_sign::digest_length"]
        [::std::mem::offset_of!(optiga_verify_sign, digest_length) - 28usize];
    ["Offset of field: optiga_verify_sign::public_key_source_type"]
        [::std::mem::offset_of!(optiga_verify_sign, public_key_source_type) - 29usize];
};
pub type optiga_verify_sign_params_t = optiga_verify_sign;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct optiga_calc_ssec {
    pub public_key: *mut public_key_from_host_t,
    pub shared_secret: *mut u8,
    pub private_key: optiga_key_id_t,
    pub export_to_host: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_calc_ssec"][::std::mem::size_of::<optiga_calc_ssec>() - 24usize];
    ["Alignment of optiga_calc_ssec"][::std::mem::align_of::<optiga_calc_ssec>() - 8usize];
    ["Offset of field: optiga_calc_ssec::public_key"]
        [::std::mem::offset_of!(optiga_calc_ssec, public_key) - 0usize];
    ["Offset of field: optiga_calc_ssec::shared_secret"]
        [::std::mem::offset_of!(optiga_calc_ssec, shared_secret) - 8usize];
    ["Offset of field: optiga_calc_ssec::private_key"]
        [::std::mem::offset_of!(optiga_calc_ssec, private_key) - 16usize];
    ["Offset of field: optiga_calc_ssec::export_to_host"]
        [::std::mem::offset_of!(optiga_calc_ssec, export_to_host) - 20usize];
};
pub type optiga_calc_ssec_params_t = optiga_calc_ssec;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct optiga_derive_key {
    pub random_data: *const u8,
    pub label: *const u8,
    pub info: *const u8,
    pub derived_key: *mut u8,
    pub input_shared_secret_oid: u16,
    pub random_data_length: u16,
    pub label_length: u16,
    pub info_length: u16,
    pub derived_key_length: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_derive_key"][::std::mem::size_of::<optiga_derive_key>() - 48usize];
    ["Alignment of optiga_derive_key"][::std::mem::align_of::<optiga_derive_key>() - 8usize];
    ["Offset of field: optiga_derive_key::random_data"]
        [::std::mem::offset_of!(optiga_derive_key, random_data) - 0usize];
    ["Offset of field: optiga_derive_key::label"]
        [::std::mem::offset_of!(optiga_derive_key, label) - 8usize];
    ["Offset of field: optiga_derive_key::info"]
        [::std::mem::offset_of!(optiga_derive_key, info) - 16usize];
    ["Offset of field: optiga_derive_key::derived_key"]
        [::std::mem::offset_of!(optiga_derive_key, derived_key) - 24usize];
    ["Offset of field: optiga_derive_key::input_shared_secret_oid"]
        [::std::mem::offset_of!(optiga_derive_key, input_shared_secret_oid) - 32usize];
    ["Offset of field: optiga_derive_key::random_data_length"]
        [::std::mem::offset_of!(optiga_derive_key, random_data_length) - 34usize];
    ["Offset of field: optiga_derive_key::label_length"]
        [::std::mem::offset_of!(optiga_derive_key, label_length) - 36usize];
    ["Offset of field: optiga_derive_key::info_length"]
        [::std::mem::offset_of!(optiga_derive_key, info_length) - 38usize];
    ["Offset of field: optiga_derive_key::derived_key_length"]
        [::std::mem::offset_of!(optiga_derive_key, derived_key_length) - 40usize];
};
pub type optiga_derive_key_params_t = optiga_derive_key;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct optiga_enc_dec_asym {
    pub processed_message_length: *mut u16,
    pub key: *const ::std::os::raw::c_void,
    pub processed_message: *mut u8,
    pub message: *const u8,
    pub message_length: u16,
    pub private_key_id: optiga_key_id_t,
    pub public_key_source_type: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_enc_dec_asym"][::std::mem::size_of::<optiga_enc_dec_asym>() - 48usize];
    ["Alignment of optiga_enc_dec_asym"][::std::mem::align_of::<optiga_enc_dec_asym>() - 8usize];
    ["Offset of field: optiga_enc_dec_asym::processed_message_length"]
        [::std::mem::offset_of!(optiga_enc_dec_asym, processed_message_length) - 0usize];
    ["Offset of field: optiga_enc_dec_asym::key"]
        [::std::mem::offset_of!(optiga_enc_dec_asym, key) - 8usize];
    ["Offset of field: optiga_enc_dec_asym::processed_message"]
        [::std::mem::offset_of!(optiga_enc_dec_asym, processed_message) - 16usize];
    ["Offset of field: optiga_enc_dec_asym::message"]
        [::std::mem::offset_of!(optiga_enc_dec_asym, message) - 24usize];
    ["Offset of field: optiga_enc_dec_asym::message_length"]
        [::std::mem::offset_of!(optiga_enc_dec_asym, message_length) - 32usize];
    ["Offset of field: optiga_enc_dec_asym::private_key_id"]
        [::std::mem::offset_of!(optiga_enc_dec_asym, private_key_id) - 36usize];
    ["Offset of field: optiga_enc_dec_asym::public_key_source_type"]
        [::std::mem::offset_of!(optiga_enc_dec_asym, public_key_source_type) - 40usize];
};
pub type optiga_encrypt_asym_params_t = optiga_enc_dec_asym;
pub type optiga_decrypt_asym_params_t = optiga_enc_dec_asym;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct optiga_set_object_protected_params {
    pub p_protected_update_buffer: *const u8,
    pub p_protected_update_buffer_length: u16,
    pub set_obj_protected_tag: optiga_set_obj_protected_tag_t,
    pub manifest_version: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_set_object_protected_params"]
        [::std::mem::size_of::<optiga_set_object_protected_params>() - 24usize];
    ["Alignment of optiga_set_object_protected_params"]
        [::std::mem::align_of::<optiga_set_object_protected_params>() - 8usize];
    ["Offset of field: optiga_set_object_protected_params::p_protected_update_buffer"][::std::mem::offset_of!(
        optiga_set_object_protected_params,
        p_protected_update_buffer
    ) - 0usize];
    ["Offset of field: optiga_set_object_protected_params::p_protected_update_buffer_length"][::std::mem::offset_of!(
        optiga_set_object_protected_params,
        p_protected_update_buffer_length
    )
        - 8usize];
    ["Offset of field: optiga_set_object_protected_params::set_obj_protected_tag"][::std::mem::offset_of!(
        optiga_set_object_protected_params,
        set_obj_protected_tag
    ) - 12usize];
    ["Offset of field: optiga_set_object_protected_params::manifest_version"]
        [::std::mem::offset_of!(optiga_set_object_protected_params, manifest_version) - 16usize];
};
pub type optiga_set_object_protected_params_t = optiga_set_object_protected_params;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct optiga_symmetric_enc_dec_params {
    pub in_data: *const u8,
    pub iv: *const u8,
    pub associated_data: *const u8,
    pub out_data: *mut u8,
    pub out_data_length: *mut u32,
    pub generated_hmac: *const u8,
    pub sent_data_length: u32,
    pub received_data_length: u32,
    pub generated_hmac_length: u32,
    pub in_data_length: u32,
    pub symmetric_key_oid: u16,
    pub iv_length: u16,
    pub associated_data_length: u16,
    pub total_input_data_length: u16,
    pub original_sequence: u8,
    pub current_sequence: u8,
    pub mode: u8,
    pub operation_mode: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_symmetric_enc_dec_params"]
        [::std::mem::size_of::<optiga_symmetric_enc_dec_params>() - 80usize];
    ["Alignment of optiga_symmetric_enc_dec_params"]
        [::std::mem::align_of::<optiga_symmetric_enc_dec_params>() - 8usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::in_data"]
        [::std::mem::offset_of!(optiga_symmetric_enc_dec_params, in_data) - 0usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::iv"]
        [::std::mem::offset_of!(optiga_symmetric_enc_dec_params, iv) - 8usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::associated_data"]
        [::std::mem::offset_of!(optiga_symmetric_enc_dec_params, associated_data) - 16usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::out_data"]
        [::std::mem::offset_of!(optiga_symmetric_enc_dec_params, out_data) - 24usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::out_data_length"]
        [::std::mem::offset_of!(optiga_symmetric_enc_dec_params, out_data_length) - 32usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::generated_hmac"]
        [::std::mem::offset_of!(optiga_symmetric_enc_dec_params, generated_hmac) - 40usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::sent_data_length"]
        [::std::mem::offset_of!(optiga_symmetric_enc_dec_params, sent_data_length) - 48usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::received_data_length"]
        [::std::mem::offset_of!(optiga_symmetric_enc_dec_params, received_data_length) - 52usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::generated_hmac_length"]
        [::std::mem::offset_of!(optiga_symmetric_enc_dec_params, generated_hmac_length) - 56usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::in_data_length"]
        [::std::mem::offset_of!(optiga_symmetric_enc_dec_params, in_data_length) - 60usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::symmetric_key_oid"]
        [::std::mem::offset_of!(optiga_symmetric_enc_dec_params, symmetric_key_oid) - 64usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::iv_length"]
        [::std::mem::offset_of!(optiga_symmetric_enc_dec_params, iv_length) - 66usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::associated_data_length"]
        [::std::mem::offset_of!(optiga_symmetric_enc_dec_params, associated_data_length) - 68usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::total_input_data_length"][::std::mem::offset_of!(
        optiga_symmetric_enc_dec_params,
        total_input_data_length
    ) - 70usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::original_sequence"]
        [::std::mem::offset_of!(optiga_symmetric_enc_dec_params, original_sequence) - 72usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::current_sequence"]
        [::std::mem::offset_of!(optiga_symmetric_enc_dec_params, current_sequence) - 73usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::mode"]
        [::std::mem::offset_of!(optiga_symmetric_enc_dec_params, mode) - 74usize];
    ["Offset of field: optiga_symmetric_enc_dec_params::operation_mode"]
        [::std::mem::offset_of!(optiga_symmetric_enc_dec_params, operation_mode) - 75usize];
};
pub type optiga_encrypt_sym_params_t = optiga_symmetric_enc_dec_params;
pub type optiga_decrypt_sym_params_t = optiga_symmetric_enc_dec_params;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct optiga_gen_symkey_params {
    pub symmetric_key: *mut ::std::os::raw::c_void,
    pub key_usage: u8,
    pub export_symmetric_key: bool_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_gen_symkey_params"]
        [::std::mem::size_of::<optiga_gen_symkey_params>() - 16usize];
    ["Alignment of optiga_gen_symkey_params"]
        [::std::mem::align_of::<optiga_gen_symkey_params>() - 8usize];
    ["Offset of field: optiga_gen_symkey_params::symmetric_key"]
        [::std::mem::offset_of!(optiga_gen_symkey_params, symmetric_key) - 0usize];
    ["Offset of field: optiga_gen_symkey_params::key_usage"]
        [::std::mem::offset_of!(optiga_gen_symkey_params, key_usage) - 8usize];
    ["Offset of field: optiga_gen_symkey_params::export_symmetric_key"]
        [::std::mem::offset_of!(optiga_gen_symkey_params, export_symmetric_key) - 9usize];
};
pub type optiga_gen_symkey_params_t = optiga_gen_symkey_params;
unsafe extern "C" {
    pub fn optiga_common_get_uint32(p_input_buffer: *const u8) -> u32;
}
unsafe extern "C" {
    pub fn optiga_common_set_uint16(p_output_buffer: *mut u8, two_byte_value: u16);
}
unsafe extern "C" {
    pub fn optiga_common_set_uint32(p_output_buffer: *mut u8, four_byte_value: u32);
}
unsafe extern "C" {
    pub fn optiga_common_get_uint16(p_input_buffer: *const u8, p_two_byte_value: *mut u16);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct optiga_cmd {
    _unused: [u8; 0],
}
pub type optiga_cmd_t = optiga_cmd;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct optiga_context {
    _unused: [u8; 0],
}
pub type optiga_context_t = optiga_context;
unsafe extern "C" {
    pub fn optiga_cmd_create(
        optiga_instance_id: u8,
        handler: callback_handler_t,
        caller_context: *mut ::std::os::raw::c_void,
    ) -> *mut optiga_cmd_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_destroy(me: *mut optiga_cmd_t) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_release_lock(me: *const optiga_cmd_t) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_open_application(
        me: *mut optiga_cmd_t,
        cmd_param: u8,
        params: *mut ::std::os::raw::c_void,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_close_application(
        me: *mut optiga_cmd_t,
        cmd_param: u8,
        params: *mut ::std::os::raw::c_void,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_get_data_object(
        me: *mut optiga_cmd_t,
        cmd_param: u8,
        params: *mut optiga_get_data_object_params_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_set_data_object(
        me: *mut optiga_cmd_t,
        cmd_param: u8,
        params: *mut optiga_set_data_object_params_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_get_random(
        me: *mut optiga_cmd_t,
        cmd_param: u8,
        params: *mut optiga_get_random_params_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_calc_hash(
        me: *mut optiga_cmd_t,
        cmd_param: u8,
        params: *mut optiga_calc_hash_params_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_calc_sign(
        me: *mut optiga_cmd_t,
        cmd_param: u8,
        params: *mut optiga_calc_sign_params_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_verify_sign(
        me: *mut optiga_cmd_t,
        cmd_param: u8,
        params: *mut optiga_verify_sign_params_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_calc_ssec(
        me: *mut optiga_cmd_t,
        cmd_param: u8,
        params: *mut optiga_calc_ssec_params_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_derive_key(
        me: *mut optiga_cmd_t,
        cmd_param: u8,
        params: *mut optiga_derive_key_params_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_gen_keypair(
        me: *mut optiga_cmd_t,
        cmd_param: u8,
        params: *mut optiga_gen_keypair_params_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_encrypt_asym(
        me: *mut optiga_cmd_t,
        cmd_param: u8,
        params: *mut optiga_encrypt_asym_params_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_decrypt_asym(
        me: *mut optiga_cmd_t,
        cmd_param: u8,
        params: *mut optiga_decrypt_asym_params_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_set_object_protected(
        me: *mut optiga_cmd_t,
        cmd_param: u8,
        params: *mut optiga_set_object_protected_params_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_encrypt_sym(
        me: *mut optiga_cmd_t,
        cmd_param: u8,
        params: *mut optiga_encrypt_sym_params_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_decrypt_sym(
        me: *mut optiga_cmd_t,
        cmd_param: u8,
        params: *mut optiga_decrypt_sym_params_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_cmd_gen_symkey(
        me: *mut optiga_cmd_t,
        cmd_param: u8,
        params: *mut optiga_gen_symkey_params_t,
    ) -> optiga_lib_status_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union optiga_util_params {
    pub optiga_set_data_object_params: optiga_set_data_object_params_t,
    pub optiga_get_data_object_params: optiga_get_data_object_params_t,
    pub optiga_set_object_protected_params: optiga_set_object_protected_params_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_util_params"][::std::mem::size_of::<optiga_util_params>() - 32usize];
    ["Alignment of optiga_util_params"][::std::mem::align_of::<optiga_util_params>() - 8usize];
    ["Offset of field: optiga_util_params::optiga_set_data_object_params"]
        [::std::mem::offset_of!(optiga_util_params, optiga_set_data_object_params) - 0usize];
    ["Offset of field: optiga_util_params::optiga_get_data_object_params"]
        [::std::mem::offset_of!(optiga_util_params, optiga_get_data_object_params) - 0usize];
    ["Offset of field: optiga_util_params::optiga_set_object_protected_params"]
        [::std::mem::offset_of!(optiga_util_params, optiga_set_object_protected_params) - 0usize];
};
pub type optiga_util_params_t = optiga_util_params;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct optiga_util {
    pub params: optiga_util_params_t,
    pub my_cmd: *mut optiga_cmd_t,
    pub caller_context: *mut ::std::os::raw::c_void,
    pub handler: callback_handler_t,
    pub instance_state: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_util"][::std::mem::size_of::<optiga_util>() - 64usize];
    ["Alignment of optiga_util"][::std::mem::align_of::<optiga_util>() - 8usize];
    ["Offset of field: optiga_util::params"][::std::mem::offset_of!(optiga_util, params) - 0usize];
    ["Offset of field: optiga_util::my_cmd"][::std::mem::offset_of!(optiga_util, my_cmd) - 32usize];
    ["Offset of field: optiga_util::caller_context"]
        [::std::mem::offset_of!(optiga_util, caller_context) - 40usize];
    ["Offset of field: optiga_util::handler"]
        [::std::mem::offset_of!(optiga_util, handler) - 48usize];
    ["Offset of field: optiga_util::instance_state"]
        [::std::mem::offset_of!(optiga_util, instance_state) - 56usize];
};
pub type optiga_util_t = optiga_util;
unsafe extern "C" {
    pub fn optiga_util_create(
        optiga_instance_id: u8,
        handler: callback_handler_t,
        caller_context: *mut ::std::os::raw::c_void,
    ) -> *mut optiga_util_t;
}
unsafe extern "C" {
    pub fn optiga_util_destroy(me: *mut optiga_util_t) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_util_open_application(
        me: *mut optiga_util_t,
        perform_restore: bool_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_util_close_application(
        me: *mut optiga_util_t,
        perform_hibernate: bool_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_util_read_data(
        me: *mut optiga_util_t,
        optiga_oid: u16,
        offset: u16,
        buffer: *mut u8,
        length: *mut u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_util_read_metadata(
        me: *mut optiga_util_t,
        optiga_oid: u16,
        buffer: *mut u8,
        length: *mut u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_util_write_data(
        me: *mut optiga_util_t,
        optiga_oid: u16,
        write_type: u8,
        offset: u16,
        buffer: *const u8,
        length: u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_util_write_metadata(
        me: *mut optiga_util_t,
        optiga_oid: u16,
        buffer: *const u8,
        length: u8,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_util_protected_update_start(
        me: *mut optiga_util_t,
        manifest_version: u8,
        manifest: *const u8,
        manifest_length: u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_util_protected_update_continue(
        me: *mut optiga_util_t,
        fragment: *const u8,
        fragment_length: u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_util_protected_update_final(
        me: *mut optiga_util_t,
        fragment: *const u8,
        fragment_length: u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_util_update_count(
        me: *mut optiga_util_t,
        optiga_counter_oid: u16,
        count: u8,
    ) -> optiga_lib_status_t;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union optiga_crypt_params {
    pub optiga_get_random_params: optiga_get_random_params_t,
    pub optiga_gen_keypair_params: optiga_gen_keypair_params_t,
    pub optiga_calc_sign_params: optiga_calc_sign_params_t,
    pub optiga_verify_sign_params: optiga_verify_sign_params_t,
    pub optiga_encrypt_asym_params: optiga_encrypt_asym_params_t,
    pub optiga_calc_hash_params: optiga_calc_hash_params_t,
    pub optiga_calc_ssec_params: optiga_calc_ssec_params_t,
    pub optiga_derive_key_params: optiga_derive_key_params_t,
    pub optiga_symmetric_enc_dec_params: optiga_encrypt_sym_params_t,
    pub optiga_gen_sym_key_params: optiga_gen_symkey_params_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_crypt_params"][::std::mem::size_of::<optiga_crypt_params>() - 80usize];
    ["Alignment of optiga_crypt_params"][::std::mem::align_of::<optiga_crypt_params>() - 8usize];
    ["Offset of field: optiga_crypt_params::optiga_get_random_params"]
        [::std::mem::offset_of!(optiga_crypt_params, optiga_get_random_params) - 0usize];
    ["Offset of field: optiga_crypt_params::optiga_gen_keypair_params"]
        [::std::mem::offset_of!(optiga_crypt_params, optiga_gen_keypair_params) - 0usize];
    ["Offset of field: optiga_crypt_params::optiga_calc_sign_params"]
        [::std::mem::offset_of!(optiga_crypt_params, optiga_calc_sign_params) - 0usize];
    ["Offset of field: optiga_crypt_params::optiga_verify_sign_params"]
        [::std::mem::offset_of!(optiga_crypt_params, optiga_verify_sign_params) - 0usize];
    ["Offset of field: optiga_crypt_params::optiga_encrypt_asym_params"]
        [::std::mem::offset_of!(optiga_crypt_params, optiga_encrypt_asym_params) - 0usize];
    ["Offset of field: optiga_crypt_params::optiga_calc_hash_params"]
        [::std::mem::offset_of!(optiga_crypt_params, optiga_calc_hash_params) - 0usize];
    ["Offset of field: optiga_crypt_params::optiga_calc_ssec_params"]
        [::std::mem::offset_of!(optiga_crypt_params, optiga_calc_ssec_params) - 0usize];
    ["Offset of field: optiga_crypt_params::optiga_derive_key_params"]
        [::std::mem::offset_of!(optiga_crypt_params, optiga_derive_key_params) - 0usize];
    ["Offset of field: optiga_crypt_params::optiga_symmetric_enc_dec_params"]
        [::std::mem::offset_of!(optiga_crypt_params, optiga_symmetric_enc_dec_params) - 0usize];
    ["Offset of field: optiga_crypt_params::optiga_gen_sym_key_params"]
        [::std::mem::offset_of!(optiga_crypt_params, optiga_gen_sym_key_params) - 0usize];
};
pub type optiga_crypt_params_t = optiga_crypt_params;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct optiga_crypt {
    pub params: optiga_crypt_params_t,
    pub my_cmd: *mut optiga_cmd_t,
    pub caller_context: *mut ::std::os::raw::c_void,
    pub handler: callback_handler_t,
    pub instance_state: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_crypt"][::std::mem::size_of::<optiga_crypt>() - 112usize];
    ["Alignment of optiga_crypt"][::std::mem::align_of::<optiga_crypt>() - 8usize];
    ["Offset of field: optiga_crypt::params"]
        [::std::mem::offset_of!(optiga_crypt, params) - 0usize];
    ["Offset of field: optiga_crypt::my_cmd"]
        [::std::mem::offset_of!(optiga_crypt, my_cmd) - 80usize];
    ["Offset of field: optiga_crypt::caller_context"]
        [::std::mem::offset_of!(optiga_crypt, caller_context) - 88usize];
    ["Offset of field: optiga_crypt::handler"]
        [::std::mem::offset_of!(optiga_crypt, handler) - 96usize];
    ["Offset of field: optiga_crypt::instance_state"]
        [::std::mem::offset_of!(optiga_crypt, instance_state) - 104usize];
};
pub type optiga_crypt_t = optiga_crypt;
unsafe extern "C" {
    pub fn optiga_crypt_create(
        optiga_instance_id: u8,
        handler: callback_handler_t,
        caller_context: *mut ::std::os::raw::c_void,
    ) -> *mut optiga_crypt_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_destroy(me: *mut optiga_crypt_t) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_random(
        me: *mut optiga_crypt_t,
        rng_type: optiga_rng_type_t,
        random_data: *mut u8,
        random_data_length: u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_hash(
        me: *mut optiga_crypt_t,
        hash_algorithm: optiga_hash_type_t,
        source_of_data_to_hash: u8,
        data_to_hash: *const ::std::os::raw::c_void,
        hash_output: *mut u8,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_hash_start(
        me: *mut optiga_crypt_t,
        hash_ctx: *mut optiga_hash_context_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_hash_update(
        me: *mut optiga_crypt_t,
        hash_ctx: *mut optiga_hash_context_t,
        source_of_data_to_hash: u8,
        data_to_hash: *const ::std::os::raw::c_void,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_hash_finalize(
        me: *mut optiga_crypt_t,
        hash_ctx: *mut optiga_hash_context_t,
        hash_output: *mut u8,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_ecc_generate_keypair(
        me: *mut optiga_crypt_t,
        curve_id: optiga_ecc_curve_t,
        key_usage: u8,
        export_private_key: bool_t,
        private_key: *mut ::std::os::raw::c_void,
        public_key: *mut u8,
        public_key_length: *mut u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_ecdsa_sign(
        me: *mut optiga_crypt_t,
        digest: *const u8,
        digest_length: u8,
        private_key: optiga_key_id_t,
        signature: *mut u8,
        signature_length: *mut u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_ecdsa_verify(
        me: *mut optiga_crypt_t,
        digest: *const u8,
        digest_length: u8,
        signature: *const u8,
        signature_length: u16,
        public_key_source_type: u8,
        public_key: *const ::std::os::raw::c_void,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_ecdh(
        me: *mut optiga_crypt_t,
        private_key: optiga_key_id_t,
        public_key: *mut public_key_from_host_t,
        export_to_host: bool_t,
        shared_secret: *mut u8,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_tls_prf(
        me: *mut optiga_crypt_t,
        type_: optiga_tls_prf_type_t,
        secret: u16,
        label: *const u8,
        label_length: u16,
        seed: *const u8,
        seed_length: u16,
        derived_key_length: u16,
        export_to_host: bool_t,
        derived_key: *mut u8,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_tls_prf_sha256(
        me: *mut optiga_crypt_t,
        secret: u16,
        label: *const u8,
        label_length: u16,
        seed: *const u8,
        seed_length: u16,
        derived_key_length: u16,
        export_to_host: bool_t,
        derived_key: *mut u8,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_tls_prf_sha384(
        me: *mut optiga_crypt_t,
        secret: u16,
        label: *const u8,
        label_length: u16,
        seed: *const u8,
        seed_length: u16,
        derived_key_length: u16,
        export_to_host: bool_t,
        derived_key: *mut u8,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_tls_prf_sha512(
        me: *mut optiga_crypt_t,
        secret: u16,
        label: *const u8,
        label_length: u16,
        seed: *const u8,
        seed_length: u16,
        derived_key_length: u16,
        export_to_host: bool_t,
        derived_key: *mut u8,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_rsa_generate_keypair(
        me: *mut optiga_crypt_t,
        key_type: optiga_rsa_key_type_t,
        key_usage: u8,
        export_private_key: bool_t,
        private_key: *mut ::std::os::raw::c_void,
        public_key: *mut u8,
        public_key_length: *mut u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_rsa_sign(
        me: *mut optiga_crypt_t,
        signature_scheme: optiga_rsa_signature_scheme_t,
        digest: *const u8,
        digest_length: u8,
        private_key: optiga_key_id_t,
        signature: *mut u8,
        signature_length: *mut u16,
        salt_length: u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_rsa_verify(
        me: *mut optiga_crypt_t,
        signature_scheme: optiga_rsa_signature_scheme_t,
        digest: *const u8,
        digest_length: u8,
        signature: *const u8,
        signature_length: u16,
        public_key_source_type: u8,
        public_key: *const ::std::os::raw::c_void,
        salt_length: u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_rsa_generate_pre_master_secret(
        me: *mut optiga_crypt_t,
        optional_data: *const u8,
        optional_data_length: u16,
        pre_master_secret_length: u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_rsa_encrypt_message(
        me: *mut optiga_crypt_t,
        encryption_scheme: optiga_rsa_encryption_scheme_t,
        message: *const u8,
        message_length: u16,
        label: *const u8,
        label_length: u16,
        public_key_source_type: u8,
        public_key: *const ::std::os::raw::c_void,
        encrypted_message: *mut u8,
        encrypted_message_length: *mut u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_rsa_encrypt_session(
        me: *mut optiga_crypt_t,
        encryption_scheme: optiga_rsa_encryption_scheme_t,
        label: *const u8,
        label_length: u16,
        public_key_source_type: u8,
        public_key: *const ::std::os::raw::c_void,
        encrypted_message: *mut u8,
        encrypted_message_length: *mut u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_rsa_decrypt_and_export(
        me: *mut optiga_crypt_t,
        encryption_scheme: optiga_rsa_encryption_scheme_t,
        encrypted_message: *const u8,
        encrypted_message_length: u16,
        label: *const u8,
        label_length: u16,
        private_key: optiga_key_id_t,
        message: *mut u8,
        message_length: *mut u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_rsa_decrypt_and_store(
        me: *mut optiga_crypt_t,
        encryption_scheme: optiga_rsa_encryption_scheme_t,
        encrypted_message: *const u8,
        encrypted_message_length: u16,
        label: *const u8,
        label_length: u16,
        private_key: optiga_key_id_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_symmetric_encrypt(
        me: *mut optiga_crypt_t,
        encryption_mode: optiga_symmetric_encryption_mode_t,
        symmetric_key_oid: optiga_key_id_t,
        plain_data: *const u8,
        plain_data_length: u32,
        iv: *const u8,
        iv_length: u16,
        associated_data: *const u8,
        associated_data_length: u16,
        encrypted_data: *mut u8,
        encrypted_data_length: *mut u32,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_symmetric_encrypt_ecb(
        me: *mut optiga_crypt_t,
        symmetric_key_oid: optiga_key_id_t,
        plain_data: *const u8,
        plain_data_length: u32,
        encrypted_data: *mut u8,
        encrypted_data_length: *mut u32,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_symmetric_encrypt_start(
        me: *mut optiga_crypt_t,
        encryption_mode: optiga_symmetric_encryption_mode_t,
        symmetric_key_oid: optiga_key_id_t,
        plain_data: *const u8,
        plain_data_length: u32,
        iv: *const u8,
        iv_length: u16,
        associated_data: *const u8,
        associated_data_length: u16,
        total_plain_data_length: u16,
        encrypted_data: *mut u8,
        encrypted_data_length: *mut u32,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_symmetric_encrypt_continue(
        me: *mut optiga_crypt_t,
        plain_data: *const u8,
        plain_data_length: u32,
        encrypted_data: *mut u8,
        encrypted_data_length: *mut u32,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_symmetric_encrypt_final(
        me: *mut optiga_crypt_t,
        plain_data: *const u8,
        plain_data_length: u32,
        encrypted_data: *mut u8,
        encrypted_data_length: *mut u32,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_symmetric_decrypt(
        me: *mut optiga_crypt_t,
        encryption_mode: optiga_symmetric_encryption_mode_t,
        symmetric_key_oid: optiga_key_id_t,
        encrypted_data: *const u8,
        encrypted_data_length: u32,
        iv: *const u8,
        iv_length: u16,
        associated_data: *const u8,
        associated_data_length: u16,
        plain_data: *mut u8,
        plain_data_length: *mut u32,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_symmetric_decrypt_ecb(
        me: *mut optiga_crypt_t,
        symmetric_key_oid: optiga_key_id_t,
        encrypted_data: *const u8,
        encrypted_data_length: u32,
        plain_data: *mut u8,
        plain_data_length: *mut u32,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_symmetric_decrypt_start(
        me: *mut optiga_crypt_t,
        encryption_mode: optiga_symmetric_encryption_mode_t,
        symmetric_key_oid: optiga_key_id_t,
        encrypted_data: *const u8,
        encrypted_data_length: u32,
        iv: *const u8,
        iv_length: u16,
        associated_data: *const u8,
        associated_data_length: u16,
        total_encrypted_data_length: u16,
        plain_data: *mut u8,
        plain_data_length: *mut u32,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_symmetric_decrypt_continue(
        me: *mut optiga_crypt_t,
        encrypted_data: *const u8,
        encrypted_data_length: u32,
        plain_data: *mut u8,
        plain_data_length: *mut u32,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_symmetric_decrypt_final(
        me: *mut optiga_crypt_t,
        encrypted_data: *const u8,
        encrypted_data_length: u32,
        plain_data: *mut u8,
        plain_data_length: *mut u32,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_hmac(
        me: *mut optiga_crypt_t,
        type_: optiga_hmac_type_t,
        secret: u16,
        input_data: *const u8,
        input_data_length: u32,
        mac: *mut u8,
        mac_length: *mut u32,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_hmac_start(
        me: *mut optiga_crypt_t,
        type_: optiga_hmac_type_t,
        secret: u16,
        input_data: *const u8,
        input_data_length: u32,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_hmac_update(
        me: *mut optiga_crypt_t,
        input_data: *const u8,
        input_data_length: u32,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_hmac_finalize(
        me: *mut optiga_crypt_t,
        input_data: *const u8,
        input_data_length: u32,
        mac: *mut u8,
        mac_length: *mut u32,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_hkdf(
        me: *mut optiga_crypt_t,
        type_: optiga_hkdf_type_t,
        secret: u16,
        salt: *const u8,
        salt_length: u16,
        info: *const u8,
        info_length: u16,
        derived_key_length: u16,
        export_to_host: bool_t,
        derived_key: *mut u8,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_hkdf_sha256(
        me: *mut optiga_crypt_t,
        secret: u16,
        salt: *const u8,
        salt_length: u16,
        info: *const u8,
        info_length: u16,
        derived_key_length: u16,
        export_to_host: bool_t,
        derived_key: *mut u8,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_hkdf_sha384(
        me: *mut optiga_crypt_t,
        secret: u16,
        salt: *const u8,
        salt_length: u16,
        info: *const u8,
        info_length: u16,
        derived_key_length: u16,
        export_to_host: bool_t,
        derived_key: *mut u8,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_hkdf_sha512(
        me: *mut optiga_crypt_t,
        secret: u16,
        salt: *const u8,
        salt_length: u16,
        info: *const u8,
        info_length: u16,
        derived_key_length: u16,
        export_to_host: bool_t,
        derived_key: *mut u8,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_symmetric_generate_key(
        me: *mut optiga_crypt_t,
        key_type: optiga_symmetric_key_type_t,
        key_usage: u8,
        export_symmetric_key: bool_t,
        symmetric_key: *mut ::std::os::raw::c_void,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_generate_auth_code(
        me: *mut optiga_crypt_t,
        rng_type: optiga_rng_type_t,
        optional_data: *const u8,
        optional_data_length: u16,
        random_data: *mut u8,
        random_data_length: u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_hmac_verify(
        me: *mut optiga_crypt_t,
        type_: optiga_hmac_type_t,
        secret: u16,
        input_data: *const u8,
        input_data_length: u32,
        hmac: *const u8,
        hmac_length: u32,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_crypt_clear_auto_state(
        me: *mut optiga_crypt_t,
        secret: u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_lib_print_string(input_string: *const char_t);
}
unsafe extern "C" {
    pub fn optiga_lib_print_string_with_newline(p_log_string: *const char_t);
}
unsafe extern "C" {
    pub fn optiga_lib_print_message(
        p_log_string: *const char_t,
        p_log_layer: *const char_t,
        p_log_color: *const char_t,
    );
}
unsafe extern "C" {
    pub fn optiga_lib_print_status(
        p_log_layer: *const char_t,
        p_log_color: *const char_t,
        return_value: u16,
    );
}
unsafe extern "C" {
    pub fn optiga_lib_print_array_hex_format(
        p_log_string: *const u8,
        length: u16,
        p_log_color: *const char_t,
    );
}
pub type pal_status_t = u16;
unsafe extern "C" {
    pub fn pal_init() -> pal_status_t;
}
unsafe extern "C" {
    pub fn pal_deinit() -> pal_status_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pal_gpio {
    pub p_gpio_hw: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pal_gpio"][::std::mem::size_of::<pal_gpio>() - 8usize];
    ["Alignment of pal_gpio"][::std::mem::align_of::<pal_gpio>() - 8usize];
    ["Offset of field: pal_gpio::p_gpio_hw"][::std::mem::offset_of!(pal_gpio, p_gpio_hw) - 0usize];
};
pub type pal_gpio_t = pal_gpio;
unsafe extern "C" {
    pub fn pal_gpio_set_high(p_gpio_context: *const pal_gpio_t);
}
unsafe extern "C" {
    pub fn pal_gpio_set_low(p_gpio_context: *const pal_gpio_t);
}
unsafe extern "C" {
    pub fn pal_gpio_init(p_gpio_context: *const pal_gpio_t) -> pal_status_t;
}
unsafe extern "C" {
    pub fn pal_gpio_deinit(p_gpio_context: *const pal_gpio_t) -> pal_status_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pal_i2c {
    pub p_i2c_hw_config: *mut ::std::os::raw::c_void,
    pub p_upper_layer_ctx: *mut ::std::os::raw::c_void,
    pub upper_layer_event_handler: *mut ::std::os::raw::c_void,
    pub slave_address: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pal_i2c"][::std::mem::size_of::<pal_i2c>() - 32usize];
    ["Alignment of pal_i2c"][::std::mem::align_of::<pal_i2c>() - 8usize];
    ["Offset of field: pal_i2c::p_i2c_hw_config"]
        [::std::mem::offset_of!(pal_i2c, p_i2c_hw_config) - 0usize];
    ["Offset of field: pal_i2c::p_upper_layer_ctx"]
        [::std::mem::offset_of!(pal_i2c, p_upper_layer_ctx) - 8usize];
    ["Offset of field: pal_i2c::upper_layer_event_handler"]
        [::std::mem::offset_of!(pal_i2c, upper_layer_event_handler) - 16usize];
    ["Offset of field: pal_i2c::slave_address"]
        [::std::mem::offset_of!(pal_i2c, slave_address) - 24usize];
};
pub type pal_i2c_t = pal_i2c;
unsafe extern "C" {
    pub fn pal_i2c_init(p_i2c_context: *const pal_i2c_t) -> pal_status_t;
}
unsafe extern "C" {
    pub fn pal_i2c_set_bitrate(p_i2c_context: *const pal_i2c_t, bitrate: u16) -> pal_status_t;
}
unsafe extern "C" {
    pub fn pal_i2c_write(
        p_i2c_context: *const pal_i2c_t,
        p_data: *mut u8,
        length: u16,
    ) -> pal_status_t;
}
unsafe extern "C" {
    pub fn pal_i2c_read(
        p_i2c_context: *const pal_i2c_t,
        p_data: *mut u8,
        length: u16,
    ) -> pal_status_t;
}
unsafe extern "C" {
    pub fn pal_i2c_deinit(p_i2c_context: *const pal_i2c_t) -> pal_status_t;
}
unsafe extern "C" {
    pub fn pal_os_datastore_read(
        datastore_id: u16,
        p_buffer: *mut u8,
        p_buffer_length: *mut u16,
    ) -> pal_status_t;
}
unsafe extern "C" {
    pub fn pal_os_datastore_write(
        datastore_id: u16,
        p_buffer: *const u8,
        length: u16,
    ) -> pal_status_t;
}
unsafe extern "C" {
    pub fn pal_os_timer_get_time_in_microseconds() -> u32;
}
unsafe extern "C" {
    pub fn pal_os_timer_get_time_in_milliseconds() -> u32;
}
unsafe extern "C" {
    pub fn pal_os_timer_delay_in_milliseconds(milliseconds: u16);
}
unsafe extern "C" {
    pub fn pal_timer_init() -> pal_status_t;
}
unsafe extern "C" {
    pub fn pal_timer_deinit() -> pal_status_t;
}
pub type ifx_i2c_context_t = __BindgenOpaqueArray<u64, 131usize>;
pub type ifx_i2c_event_handler_t = ::std::option::Option<
    unsafe extern "C" fn(
        p_ctx: *mut ifx_i2c_context,
        event: optiga_lib_status_t,
        data: *const u8,
        data_len: u16,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ifx_i2c_pl {
    pub p_tx_frame: *mut u8,
    pub upper_layer_event_handler: ifx_i2c_event_handler_t,
    pub retry_counter: u16,
    pub buffer_tx_len: u16,
    pub buffer_rx_len: u16,
    pub tx_frame_len: u16,
    pub buffer: [u8; 278usize],
    pub register_action: u8,
    pub i2c_cmd: u8,
    pub frame_action: u8,
    pub frame_state: u8,
    pub negotiate_state: u8,
    pub request_soft_reset: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ifx_i2c_pl"][::std::mem::size_of::<ifx_i2c_pl>() - 312usize];
    ["Alignment of ifx_i2c_pl"][::std::mem::align_of::<ifx_i2c_pl>() - 8usize];
    ["Offset of field: ifx_i2c_pl::p_tx_frame"]
        [::std::mem::offset_of!(ifx_i2c_pl, p_tx_frame) - 0usize];
    ["Offset of field: ifx_i2c_pl::upper_layer_event_handler"]
        [::std::mem::offset_of!(ifx_i2c_pl, upper_layer_event_handler) - 8usize];
    ["Offset of field: ifx_i2c_pl::retry_counter"]
        [::std::mem::offset_of!(ifx_i2c_pl, retry_counter) - 16usize];
    ["Offset of field: ifx_i2c_pl::buffer_tx_len"]
        [::std::mem::offset_of!(ifx_i2c_pl, buffer_tx_len) - 18usize];
    ["Offset of field: ifx_i2c_pl::buffer_rx_len"]
        [::std::mem::offset_of!(ifx_i2c_pl, buffer_rx_len) - 20usize];
    ["Offset of field: ifx_i2c_pl::tx_frame_len"]
        [::std::mem::offset_of!(ifx_i2c_pl, tx_frame_len) - 22usize];
    ["Offset of field: ifx_i2c_pl::buffer"][::std::mem::offset_of!(ifx_i2c_pl, buffer) - 24usize];
    ["Offset of field: ifx_i2c_pl::register_action"]
        [::std::mem::offset_of!(ifx_i2c_pl, register_action) - 302usize];
    ["Offset of field: ifx_i2c_pl::i2c_cmd"]
        [::std::mem::offset_of!(ifx_i2c_pl, i2c_cmd) - 303usize];
    ["Offset of field: ifx_i2c_pl::frame_action"]
        [::std::mem::offset_of!(ifx_i2c_pl, frame_action) - 304usize];
    ["Offset of field: ifx_i2c_pl::frame_state"]
        [::std::mem::offset_of!(ifx_i2c_pl, frame_state) - 305usize];
    ["Offset of field: ifx_i2c_pl::negotiate_state"]
        [::std::mem::offset_of!(ifx_i2c_pl, negotiate_state) - 306usize];
    ["Offset of field: ifx_i2c_pl::request_soft_reset"]
        [::std::mem::offset_of!(ifx_i2c_pl, request_soft_reset) - 307usize];
};
pub type ifx_i2c_pl_t = ifx_i2c_pl;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ifx_i2c_dl {
    pub p_tx_frame_buffer: *mut u8,
    pub p_rx_frame_buffer: *mut u8,
    pub frame_start_time: u32,
    pub upper_layer_event_handler: ifx_i2c_event_handler_t,
    pub data_poll_timeout: u32,
    pub tx_buffer_size: u16,
    pub rx_buffer_size: u16,
    pub state: u8,
    pub tx_seq_nr: u8,
    pub rx_seq_nr: u8,
    pub action_rx_only: u8,
    pub retransmit_counter: u8,
    pub error: u8,
    pub resynced: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ifx_i2c_dl"][::std::mem::size_of::<ifx_i2c_dl>() - 48usize];
    ["Alignment of ifx_i2c_dl"][::std::mem::align_of::<ifx_i2c_dl>() - 8usize];
    ["Offset of field: ifx_i2c_dl::p_tx_frame_buffer"]
        [::std::mem::offset_of!(ifx_i2c_dl, p_tx_frame_buffer) - 0usize];
    ["Offset of field: ifx_i2c_dl::p_rx_frame_buffer"]
        [::std::mem::offset_of!(ifx_i2c_dl, p_rx_frame_buffer) - 8usize];
    ["Offset of field: ifx_i2c_dl::frame_start_time"]
        [::std::mem::offset_of!(ifx_i2c_dl, frame_start_time) - 16usize];
    ["Offset of field: ifx_i2c_dl::upper_layer_event_handler"]
        [::std::mem::offset_of!(ifx_i2c_dl, upper_layer_event_handler) - 24usize];
    ["Offset of field: ifx_i2c_dl::data_poll_timeout"]
        [::std::mem::offset_of!(ifx_i2c_dl, data_poll_timeout) - 32usize];
    ["Offset of field: ifx_i2c_dl::tx_buffer_size"]
        [::std::mem::offset_of!(ifx_i2c_dl, tx_buffer_size) - 36usize];
    ["Offset of field: ifx_i2c_dl::rx_buffer_size"]
        [::std::mem::offset_of!(ifx_i2c_dl, rx_buffer_size) - 38usize];
    ["Offset of field: ifx_i2c_dl::state"][::std::mem::offset_of!(ifx_i2c_dl, state) - 40usize];
    ["Offset of field: ifx_i2c_dl::tx_seq_nr"]
        [::std::mem::offset_of!(ifx_i2c_dl, tx_seq_nr) - 41usize];
    ["Offset of field: ifx_i2c_dl::rx_seq_nr"]
        [::std::mem::offset_of!(ifx_i2c_dl, rx_seq_nr) - 42usize];
    ["Offset of field: ifx_i2c_dl::action_rx_only"]
        [::std::mem::offset_of!(ifx_i2c_dl, action_rx_only) - 43usize];
    ["Offset of field: ifx_i2c_dl::retransmit_counter"]
        [::std::mem::offset_of!(ifx_i2c_dl, retransmit_counter) - 44usize];
    ["Offset of field: ifx_i2c_dl::error"][::std::mem::offset_of!(ifx_i2c_dl, error) - 45usize];
    ["Offset of field: ifx_i2c_dl::resynced"]
        [::std::mem::offset_of!(ifx_i2c_dl, resynced) - 46usize];
};
pub type ifx_i2c_dl_t = ifx_i2c_dl;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ifx_i2c_tl {
    pub p_actual_packet: *mut u8,
    pub p_recv_packet_buffer: *mut u8,
    pub p_recv_packet_buffer_length: *mut u16,
    pub upper_layer_event_handler: ifx_i2c_event_handler_t,
    pub api_start_time: u32,
    pub total_recv_length: u16,
    pub actual_packet_length: u16,
    pub packet_offset: u16,
    pub max_packet_length: u16,
    pub error_event: optiga_lib_status_t,
    pub state: u8,
    pub chaining_error_count: u8,
    pub master_chaining_error_count: u8,
    pub previous_chaining: u8,
    pub transmission_completed: u8,
    pub payload_offset: u8,
    pub tx_payload_offset: u8,
    pub initialization_state: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ifx_i2c_tl"][::std::mem::size_of::<ifx_i2c_tl>() - 56usize];
    ["Alignment of ifx_i2c_tl"][::std::mem::align_of::<ifx_i2c_tl>() - 8usize];
    ["Offset of field: ifx_i2c_tl::p_actual_packet"]
        [::std::mem::offset_of!(ifx_i2c_tl, p_actual_packet) - 0usize];
    ["Offset of field: ifx_i2c_tl::p_recv_packet_buffer"]
        [::std::mem::offset_of!(ifx_i2c_tl, p_recv_packet_buffer) - 8usize];
    ["Offset of field: ifx_i2c_tl::p_recv_packet_buffer_length"]
        [::std::mem::offset_of!(ifx_i2c_tl, p_recv_packet_buffer_length) - 16usize];
    ["Offset of field: ifx_i2c_tl::upper_layer_event_handler"]
        [::std::mem::offset_of!(ifx_i2c_tl, upper_layer_event_handler) - 24usize];
    ["Offset of field: ifx_i2c_tl::api_start_time"]
        [::std::mem::offset_of!(ifx_i2c_tl, api_start_time) - 32usize];
    ["Offset of field: ifx_i2c_tl::total_recv_length"]
        [::std::mem::offset_of!(ifx_i2c_tl, total_recv_length) - 36usize];
    ["Offset of field: ifx_i2c_tl::actual_packet_length"]
        [::std::mem::offset_of!(ifx_i2c_tl, actual_packet_length) - 38usize];
    ["Offset of field: ifx_i2c_tl::packet_offset"]
        [::std::mem::offset_of!(ifx_i2c_tl, packet_offset) - 40usize];
    ["Offset of field: ifx_i2c_tl::max_packet_length"]
        [::std::mem::offset_of!(ifx_i2c_tl, max_packet_length) - 42usize];
    ["Offset of field: ifx_i2c_tl::error_event"]
        [::std::mem::offset_of!(ifx_i2c_tl, error_event) - 44usize];
    ["Offset of field: ifx_i2c_tl::state"][::std::mem::offset_of!(ifx_i2c_tl, state) - 46usize];
    ["Offset of field: ifx_i2c_tl::chaining_error_count"]
        [::std::mem::offset_of!(ifx_i2c_tl, chaining_error_count) - 47usize];
    ["Offset of field: ifx_i2c_tl::master_chaining_error_count"]
        [::std::mem::offset_of!(ifx_i2c_tl, master_chaining_error_count) - 48usize];
    ["Offset of field: ifx_i2c_tl::previous_chaining"]
        [::std::mem::offset_of!(ifx_i2c_tl, previous_chaining) - 49usize];
    ["Offset of field: ifx_i2c_tl::transmission_completed"]
        [::std::mem::offset_of!(ifx_i2c_tl, transmission_completed) - 50usize];
    ["Offset of field: ifx_i2c_tl::payload_offset"]
        [::std::mem::offset_of!(ifx_i2c_tl, payload_offset) - 51usize];
    ["Offset of field: ifx_i2c_tl::tx_payload_offset"]
        [::std::mem::offset_of!(ifx_i2c_tl, tx_payload_offset) - 52usize];
    ["Offset of field: ifx_i2c_tl::initialization_state"]
        [::std::mem::offset_of!(ifx_i2c_tl, initialization_state) - 53usize];
};
pub type ifx_i2c_tl_t = ifx_i2c_tl;
#[repr(C)]
#[repr(align(8))]
pub struct ifx_i2c_context {
    pub _bindgen_opaque_blob: [u64; 131usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ifx_i2c_context"][::std::mem::size_of::<ifx_i2c_context>() - 1048usize];
    ["Alignment of ifx_i2c_context"][::std::mem::align_of::<ifx_i2c_context>() - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct optiga_comms {
    pub p_pal_os_event_ctx: *mut ::std::os::raw::c_void,
    pub p_comms_ctx: *mut ::std::os::raw::c_void,
    pub p_upper_layer_ctx: *mut ::std::os::raw::c_void,
    pub upper_layer_handler: upper_layer_callback_t,
    pub instance_init_state: u8,
    pub state: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of optiga_comms"][::std::mem::size_of::<optiga_comms>() - 40usize];
    ["Alignment of optiga_comms"][::std::mem::align_of::<optiga_comms>() - 8usize];
    ["Offset of field: optiga_comms::p_pal_os_event_ctx"]
        [::std::mem::offset_of!(optiga_comms, p_pal_os_event_ctx) - 0usize];
    ["Offset of field: optiga_comms::p_comms_ctx"]
        [::std::mem::offset_of!(optiga_comms, p_comms_ctx) - 8usize];
    ["Offset of field: optiga_comms::p_upper_layer_ctx"]
        [::std::mem::offset_of!(optiga_comms, p_upper_layer_ctx) - 16usize];
    ["Offset of field: optiga_comms::upper_layer_handler"]
        [::std::mem::offset_of!(optiga_comms, upper_layer_handler) - 24usize];
    ["Offset of field: optiga_comms::instance_init_state"]
        [::std::mem::offset_of!(optiga_comms, instance_init_state) - 32usize];
    ["Offset of field: optiga_comms::state"][::std::mem::offset_of!(optiga_comms, state) - 33usize];
};
pub type optiga_comms_t = optiga_comms;
unsafe extern "C" {
    pub fn optiga_comms_create(
        callback: callback_handler_t,
        context: *mut ::std::os::raw::c_void,
    ) -> *mut optiga_comms_t;
}
unsafe extern "C" {
    pub fn optiga_comms_destroy(optiga_comms: *mut optiga_comms_t);
}
unsafe extern "C" {
    pub fn optiga_comms_set_callback_context(
        p_optiga_comms: *mut optiga_comms_t,
        context: *mut ::std::os::raw::c_void,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_comms_set_callback_handler(
        p_optiga_comms: *mut optiga_comms_t,
        handler: callback_handler_t,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_comms_open(p_ctx: *mut optiga_comms_t) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_comms_reset(p_ctx: *mut optiga_comms_t, reset_type: u8) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_comms_transceive(
        p_ctx: *mut optiga_comms_t,
        p_tx_data: *const u8,
        tx_data_length: u16,
        p_rx_data: *mut u8,
        p_rx_data_len: *mut u16,
    ) -> optiga_lib_status_t;
}
unsafe extern "C" {
    pub fn optiga_comms_close(p_ctx: *mut optiga_comms_t) -> optiga_lib_status_t;
}
pub type register_callback =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pal_os_event {
    pub callback_ctx: *mut ::std::os::raw::c_void,
    pub os_timer: *mut ::std::os::raw::c_void,
    pub is_event_triggered: bool_t,
    pub timeout_us: u32,
    pub sync_flag: u8,
    pub callback_registered: register_callback,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pal_os_event"][::std::mem::size_of::<pal_os_event>() - 40usize];
    ["Alignment of pal_os_event"][::std::mem::align_of::<pal_os_event>() - 8usize];
    ["Offset of field: pal_os_event::callback_ctx"]
        [::std::mem::offset_of!(pal_os_event, callback_ctx) - 0usize];
    ["Offset of field: pal_os_event::os_timer"]
        [::std::mem::offset_of!(pal_os_event, os_timer) - 8usize];
    ["Offset of field: pal_os_event::is_event_triggered"]
        [::std::mem::offset_of!(pal_os_event, is_event_triggered) - 16usize];
    ["Offset of field: pal_os_event::timeout_us"]
        [::std::mem::offset_of!(pal_os_event, timeout_us) - 20usize];
    ["Offset of field: pal_os_event::sync_flag"]
        [::std::mem::offset_of!(pal_os_event, sync_flag) - 24usize];
    ["Offset of field: pal_os_event::callback_registered"]
        [::std::mem::offset_of!(pal_os_event, callback_registered) - 32usize];
};
pub type pal_os_event_t = pal_os_event;
unsafe extern "C" {
    pub fn pal_os_event_create(
        callback: register_callback,
        callback_args: *mut ::std::os::raw::c_void,
    ) -> *mut pal_os_event_t;
}
unsafe extern "C" {
    pub fn pal_os_event_destroy(pal_os_event: *mut pal_os_event_t);
}
unsafe extern "C" {
    pub fn pal_os_event_register_callback_oneshot(
        p_pal_os_event: *mut pal_os_event_t,
        callback: register_callback,
        callback_args: *mut ::std::os::raw::c_void,
        time_us: u32,
    );
}
unsafe extern "C" {
    pub fn pal_os_event_trigger_registered_callback();
}
unsafe extern "C" {
    pub fn pal_os_event_start(
        p_pal_os_event: *mut pal_os_event_t,
        callback: register_callback,
        callback_args: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn pal_os_event_stop(p_pal_os_event: *mut pal_os_event_t);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pal_linux {
    pub i2c_if: *const ::std::os::raw::c_char,
    pub i2c_handle: ::std::os::raw::c_int,
    pub upper_layer_event_handler: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pal_linux"][::std::mem::size_of::<pal_linux>() - 24usize];
    ["Alignment of pal_linux"][::std::mem::align_of::<pal_linux>() - 8usize];
    ["Offset of field: pal_linux::i2c_if"][::std::mem::offset_of!(pal_linux, i2c_if) - 0usize];
    ["Offset of field: pal_linux::i2c_handle"]
        [::std::mem::offset_of!(pal_linux, i2c_handle) - 8usize];
    ["Offset of field: pal_linux::upper_layer_event_handler"]
        [::std::mem::offset_of!(pal_linux, upper_layer_event_handler) - 16usize];
};
pub type pal_linux_t = pal_linux;
pub type gpio_pin_t = u16;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pal_linux_gpio {
    pub pin_nr: gpio_pin_t,
    pub fd: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pal_linux_gpio"][::std::mem::size_of::<pal_linux_gpio>() - 8usize];
    ["Alignment of pal_linux_gpio"][::std::mem::align_of::<pal_linux_gpio>() - 4usize];
    ["Offset of field: pal_linux_gpio::pin_nr"]
        [::std::mem::offset_of!(pal_linux_gpio, pin_nr) - 0usize];
    ["Offset of field: pal_linux_gpio::fd"][::std::mem::offset_of!(pal_linux_gpio, fd) - 4usize];
};
pub type pal_linux_gpio_t = pal_linux_gpio;
unsafe extern "C" {
    pub fn trustm_sys_configure(dev: *const ::std::os::raw::c_char, addr: u8);
}
