//! Raw FFI bindings to the Infineon OPTIGA™ Trust M host library.
//!
//! The C library (git submodule `optiga-trust-m`) is compiled by this crate's
//! build script together with its Linux I2C platform layer, so there is
//! nothing to install: `cargo build` produces a self-contained static library
//! with libc as its only dependency.
//!
//! `src/bindings.rs` is generated by bindgen from `csrc/wrapper.h` and
//! committed, so consumers and cross builds do not need libclang. Regenerate
//! with `just bindgen` after bumping the submodule.
//!
//! Everything here is `unsafe` and mirrors the C API one to one, including
//! its asynchronous callback model. The `trustm` crate provides a safe,
//! blocking wrapper on top.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(clippy::all)]

include!("bindings.rs");
