/*
 * OPTIGA Trust M host library configuration for trustm-sys.
 *
 * Replaces optiga_lib_config_m_v3.h via -DOPTIGA_LIB_EXTERNAL. Every crypto
 * command of the chip is enabled. What is deliberately off:
 *  - OPTIGA_COMMS_SHIELDED_CONNECTION: encrypts the I2C link with a host-side
 *    secret. It is the only thing that pulls mbedTLS into the build.
 *  - OPTIGA_LIB_ENABLE_LOGGING: printf logging from inside the library.
 */
#ifndef TRUSTM_SYS_CONFIG_H
#define TRUSTM_SYS_CONFIG_H

#define OPTIGA_CRYPT_RANDOM_ENABLED
#define OPTIGA_CRYPT_HASH_ENABLED
#define OPTIGA_CRYPT_ECC_GENERATE_KEYPAIR_ENABLED
#define OPTIGA_CRYPT_ECDSA_SIGN_ENABLED
#define OPTIGA_CRYPT_ECDSA_VERIFY_ENABLED
#define OPTIGA_CRYPT_ECDH_ENABLED
#define OPTIGA_CRYPT_ECC_NIST_P_521_ENABLED
#define OPTIGA_CRYPT_ECC_BRAINPOOL_P_R1_ENABLED
#define OPTIGA_CRYPT_TLS_PRF_SHA256_ENABLED
#define OPTIGA_CRYPT_TLS_PRF_SHA384_ENABLED
#define OPTIGA_CRYPT_TLS_PRF_SHA512_ENABLED
#define OPTIGA_CRYPT_RSA_GENERATE_KEYPAIR_ENABLED
#define OPTIGA_CRYPT_RSA_SIGN_ENABLED
#define OPTIGA_CRYPT_RSA_VERIFY_ENABLED
#define OPTIGA_CRYPT_RSA_ENCRYPT_ENABLED
#define OPTIGA_CRYPT_RSA_DECRYPT_ENABLED
#define OPTIGA_CRYPT_RSA_PRE_MASTER_SECRET_ENABLED
#define OPTIGA_CRYPT_RSA_SSA_SHA512_ENABLED
#define OPTIGA_CRYPT_SYM_ENCRYPT_ENABLED
#define OPTIGA_CRYPT_SYM_DECRYPT_ENABLED
#define OPTIGA_CRYPT_HMAC_ENABLED
#define OPTIGA_CRYPT_HKDF_ENABLED
#define OPTIGA_CRYPT_SYM_GENERATE_KEY_ENABLED
#define OPTIGA_CRYPT_GENERATE_AUTH_CODE_ENABLED
#define OPTIGA_CRYPT_HMAC_VERIFY_ENABLED
#define OPTIGA_CRYPT_CLEAR_AUTO_STATE_ENABLED

#define OPTIGA_COMMS_DEFAULT_PROTECTION_LEVEL OPTIGA_COMMS_NO_PROTECTION
/* 1 = soft reset over I2C. No reset/VDD GPIO needed. */
#define OPTIGA_COMMS_DEFAULT_RESET_TYPE (1U)

#define OPTIGA_LIB_DEBUG_NULL_CHECK
#define OPTIGA_CMD_MAX_REGISTRATIONS (0x06)
#define OPTIGA_MAX_COMMS_BUFFER_SIZE (0x615)
#define OPTIGA_PAL_INIT_ENABLED

#endif /* TRUSTM_SYS_CONFIG_H */
